version: 2
updates:
  - package-ecosystem: pip
    directory: /sdk/python
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - automated

  - package-ecosystem: pip
    directory: /codegen
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - automated

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
      - automated
